name: Health Check

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check staging health
        run: |
          response=$(curl -s https://staging.iglesiadamasco.com/api/health)
          if [[ $(echo $response | jq -r '.status') != "healthy" ]]; then
            echo "Staging health check failed"
            exit 1
          fi

      - name: Check production health
        run: |
          response=$(curl -s https://iglesiadamasco.com/api/health)
          if [[ $(echo $response | jq -r '.status') != "healthy" ]]; then
            echo "Production health check failed"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Health Check Failed',
              body: 'One or more health checks have failed. Please investigate.',
              labels: ['health-check', 'urgent']
            }); 